id: AFF6467D6
title: Prayer for Peace and Stability in Tibet
type: translation
pechas:
- I68186785
- ID6145CF7
- IAAAE6EEF
- IE0954FCF
- I36940848
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:00:09.980954
  last_modified_at: 2023-01-04 12:00:09.980976
  collections:
  - Jamgön Kongtrul Lodrö Thaye Series
  - Works of Tibetan Masters
alignment_to_base:
  I68186785/2D50: EF00
  ID6145CF7/C3ED: EF00
  IAAAE6EEF/18C9: EF00
  IE0954FCF/2809: EF00
  I36940848/0EE4: EF00
